language: python

sudo: false

python:
  - "3.6.2"

# command to install dependencies
install:
  - pip install -r requirements.txt

before_script:
  - python manage.py migrate
  - python manage.py runserver &

script:
  - null  
